title: Silas Zehnder
email: szehnder@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
  Silas Zehnder is a software engineer always looking for new
  opportunities. If you believe I would be a good fit for your
  team, feel free to download my resume and shoot me an email.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://szehnder.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  silaszehnder

# ADDED CONFIGURATIONS
timezone: America/Denver

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude: ['.gitignore', 'CNAME']
