---
title: Silas Zehnder
email: silaszehnder@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    2023
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://szehnder.com"  # the base hostname & protocol for your site, e.g. http://example.com
github_username: silaszehnder
timezone: America/Detroit

permalink: /:categories/:title:output_ext

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude: ['.gitignore', 'CNAME']
